export const CajasUsuarios = (id: any) => {
    const fecha = new Date();
    return [
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 1,
            position: "a",
            valor: 5,
            fecha,
            estado: false,
            activo: false,
            consecutivo: null,
            name: "CAJA PARTICIPANTE",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 2,
            position: "b",
            valor: 10,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA INVERSOR",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 3,
            position: "c",
            valor: 20,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA CONSTRUCTOR",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 4,
            position: "d",
            valor: 40,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA TRIUNFADOR",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 5,
            position: "e",
            valor: 80,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA MASTER",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 6,
            position: "f",
            valor: 160,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA BRONCE",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 7,
            position: "g",
            valor: 320,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA CONSTRUCTOR",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 8,
            position: "h",
            valor: 640,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA ORO",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 9,
            position: "i",
            valor: 1280,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA RUBY",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 10,
            position: "j",
            valor: 2560,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA ZAFIRO",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 11,
            position: "k",
            valor: 5120,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA ESMERALDA",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 12,
            position: "l",
            valor: 10240,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA DIAMANTE",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 13,
            position: "m",
            valor: 20480,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA DIAMANTE MASTER",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 14,
            position: "n",
            valor: 40960,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA DIAMANTE CORONA",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 15,
            position: "o",
            valor: 81920,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA EMBAJADO",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 16,
            position: "p",
            valor: 163840,
            fecha,
            estado: true,
            activo: false,
            consecutivo: null,
            name: "CAJA MAGNATE",
        },
    ];
};

export const CajasEmpresas = (id: any) => {
    let fecha = new Date();
    return [
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 1,
            position: "a",
            valor: 5,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA PARTICIPANTE",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 2,
            position: "b",
            valor: 10,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA INVERSOR",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 3,
            position: "c",
            valor: 20,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA CONSTRUCTOR",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 4,
            position: "d",
            valor: 40,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA TRIUNFADOR",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 5,
            position: "e",
            valor: 80,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA MASTER",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 6,
            position: "f",
            valor: 160,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA BRONCE",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 7,
            position: "g",
            valor: 320,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA CONSTRUCTOR",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 8,
            position: "h",
            valor: 640,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA ORO",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 9,
            position: "i",
            valor: 1280,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA RUBY",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 10,
            position: "j",
            valor: 2560,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA ZAFIRO",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 11,
            position: "k",
            valor: 5120,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA ESMERALDA",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 12,
            position: "l",
            valor: 10240,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA DIAMANTE",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 13,
            position: "m",
            valor: 20480,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA DIAMANTE MASTER",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 14,
            position: "n",
            valor: 40960,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA DIAMANTE CORONA",
        },
        {
            usuario: id,
            p1: null,
            p2: null,
            p3: null,
            nivel: 15,
            position: "o",
            valor: 81920,
            fecha,
            estado: true,
            activo: true,
            consecutivo: 1,
            name: "CAJA EMBAJADO",
        },
    ];
};
