export const pricesNFT = [
    { price: 15, commission: 1.1, dias: 200, limit: 500 },
    { price: 75, commission: 1.2, dias: 400, limit: 250 },
    { price: 155, commission: 1.4, dias: 400, limit: 100 },
    { price: 315, commission: 1.6, dias: 400, limit: 50 },
    { price: 635, commission: 1.8, dias: 400, limit: 50 },
    { price: 1275, commission: 2, dias: 400, limit: 50 },
]
interface aa {
    nivel: number;
    position: string;
    valor: number;
    activo: boolean;
    comprado: boolean;
    consecutivo: any;
    name: string;
}
export const nftTable: aa[] = [
    {
        nivel: 1,
        position: "a",
        valor: 5,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA AMATEUR",
    },
    {
        nivel: 2,
        position: "b",
        valor: 10,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA IRON",
    },
    {
        nivel: 3,
        position: "c",
        valor: 20,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA BRONCE",
    },
    {
        nivel: 4,
        position: "d",
        valor: 40,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA SILVER",
    },
    {
        nivel: 5,
        position: "e",
        valor: 80,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA GOLD",
    },
    {
        nivel: 6,
        position: "f",
        valor: 160,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA PLATINUM",
    },
    {
        nivel: 7,
        position: "g",
        valor: 320,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA EMERALD",
    },
    {
        nivel: 8,
        position: "h",
        valor: 640,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA DIAMOND",
    },
    {
        nivel: 9,
        position: "i",
        valor: 1280,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA CRISTAL",
    },
    {
        nivel: 10,
        position: "j",
        valor: 2560,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA TITAN",
    },
    {
        nivel: 11,
        position: "k",
        valor: 5120,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA EMBAJADOR",
    },
    {
        nivel: 12,
        position: "l",
        valor: 10240,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA CORONA",
    },
    {
        nivel: 13,
        position: "m",
        valor: 20480,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA MASTER",
    },
    {
        nivel: 14,
        position: "n",
        valor: 40960,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA GRAMD MASTER",
    },
    {
        nivel: 15,
        position: "o",
        valor: 81920,
        comprado: false,
        activo: false,
        consecutivo: null,
        name: "LIGA CHALLENGER",
    },
];